### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by perstromqvist** [ttopholm/homebridge-nordpool#7]
```
[09/05/2023, 13:17:58] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///var/lib/homebridge/node_modules/homebridge-nordpool/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Prices.getValues (file:///var/lib/homebridge/node_modules/homebridge-nordpool/node_modules/nordpool/lib/prices.js:83:20)
```
Error resulting in a SIGTERM and a reboot of the homebridge.

**Comment by ttopholm** [comment]
Is rewriting the plugin a bit, so this should fix it.

**Comment by perstromqvist** [comment]
Will this update hit the homebridge gui as an update too?

Can see that the version is still 1.0.0 in homebridge.

Sincerely
/P

sön 6 aug. 2023 kl. 22:00 skrev Tue Topholm ***@***.***>:
